---
- name: Install python3, docker, docker-compose
  hosts: ec2_server
  become: yes
  tasks:
    - name: Make sure  python3 and docker are installed
      vars: 
        ansible_python_interpreter: /user/bin/python
      apt:
       name: 
         - python3
         - docker
       update_cache: yes
       state: present
    - name: Install docker-compose
      get_url:
         url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
         dest: /usr/local/bin/docker-compose
         mode: +x
    - name: start docker demon
      systemd: 
         name: docker
         state: started 
    - name: Install docker python module
      pip: 
        name: docker

- name: add ubuntu user to docker group
  hosts: ec2_server
  become: true
  tasks: 
    - name: add user to docker group
      user: 
        name: ubuntu
        groups: docker 
        append: yes 
    - name: reconnect to server session
      meta: reset_connection