---
- name: Install node and npm
  hosts: ec2_server
  become: true
  become_method: sudo
  tasks: 
    - name: Update app repo and cache 
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install java 8
      apt: name=openjdk-8-jre-headless 
    - name: install net tools
      apt: name=net-tools
    - name: Install required packaged
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - acl
        - python3-pip

- name: Download and unpack Nexus installer 
  hosts: ec2_server
  tasks:
    - name: check nexus folder stat
      stat:
        path: /home/ubuntu/nexus
      register: stat_result
    - name: download nexus 
      get_url: 
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /home/ubuntu/
      register: download_result
    - debug: msg={{download_result}}
    - name: untar Nexus installer 
      unarchive: 
        src: "{{download_result.dest}}" 
        dest: /home/ubuntu/
        remote_src: true
      when: not stat_result.stat.exists
    - name: find the nexus folder
      find: 
        path: /home/ubuntu
        pattern: "nexus-*"
        file_type: directory
      register: find_result
    - debug: msg={{find_result}}
    - name: rename nexus folder
      shell: mv {{find_result.files[0].path}} /home/ubuntu/nexus
      when: not stat_result.stat.exists

- name: Create nexus user to own nexus folder
  hosts:  ec2_server
  become: true
  become_method: sudo
  tasks: 
    - name: Ensure group nexus exists
      group: 
        name: nexus
        state: present
    - name: create nexus user
      user: 
        name: nexus
        comment: create user 
        group: nexus
    - name: Make nexus user owner of nexus folder
      file: 
        path: /home/ubuntu/nexus
        state: directory
        owner: nexus
        group: nexus
        mode: '0777'
        recurse: true
    - name: Make nexus user owner of sonatype-work folder
      file: 
        path: /home/ubuntu/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        mode: '0777'
        recurse: true

- name: Start nexus with nexus user
  hosts:  ec2_server
  become: True
  become_user: nexus     
  tasks:
    - name: Set run_as_user nexus
      ansible.builtin.lineinfile:
        path: /home/ubuntu/nexus/bin/nexus.rc
        regexp: '^#run_as_user=""'
        line: run_as_user="nexus"
    - name: Start nexus
      ansible.builtin.command: /home/ubuntu/nexus/bin/nexus start
- name: Verify nexus running
  hosts: ec2_server
  become: true
  become_user: nexus
  tasks:
    - name: Check with ps
      ansible.builtin.shell: ps aux | grep nexus
      register: app_status
    - ansible.builtin.debug: msg={{app_status.stdout_lines}}
    - name: Wait one minute
      ansible.builtin.pause:
        minutes: 1
    - name: Check with netstat
      ansible.builtin.shell: netstat -plnt
      register: app_status
    - ansible.builtin.debug: msg={{app_status.stdout_lines}}
